---
title: "Lab6, Group A2, Visualization 732A98"
author: "Hugo Knape & Yifan Ding"
date: "10/7/2020"
output: html_document
#  html_document: default
#  pdf_document: default
##runtime: shinny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, echo = FALSE)
```


```{r, warning = FALSE, include = FALSE}

library(ggraph)
library(igraph)
library(visNetwork)

```

# Statement of contribution

We have done most parts together, but Yifan mainly contributed to assignment 1. Hugo mainly contributed to assignment 2.

# Assignment 1
### Assignment 1.1 


```{r, warning=FALSE, echo=TRUE, message=TRUE}

nodes <- read.table('trainMeta.dat')
links <- read.table('trainData.dat')
links <- aggregate(links[,3], links[,-3], mean)
colnames(links) <- c("from", "to", "width")
links <- links[order(links$from, links$to),]
rownames(links) <- NULL
links$weight<-links$width
colnames(nodes) <- c("label", "group")

nodes$id <- c(1:nrow(nodes))
nodes <- nodes[, c(3,1,2)]
weight<-lapply(c(1:nrow(nodes)), function(x){return(sum(links$from == x))})
nodes$value <- as.numeric(weight)
#nodes$label=nodes$media
#net <- graph_from_data_frame(d=links, vertices=nodes, directed=T)
#visIgraph(net)
#nodes<-nodes[nodes$value!=0, ]
p <- visNetwork(nodes, links)%>%visIgraphLayout()%>%
  visPhysics(solver="repulsion")%>% 
  visOptions(highlightNearest = list(enabled = TRUE, 
             algorithm = "hierarchical" ),
             nodesIdSelection = list(enabled = TRUE),
             selectedBy = list(variable = "weight", selected = 1, highlight=TRUE)) 
p



```


### Assignment 1.2

```{r, warning=FALSE, echo=FALSE}
p <- visNetwork(nodes, links)%>%
  visPhysics(solver="repulsion")%>%visIgraphLayout()%>% 
  visOptions(highlightNearest = list(enabled = TRUE, 
             algorithm = "hierarchical",hover = TRUE, degree = 2 ),
             nodesIdSelection = list(enabled = TRUE),
             selectedBy = list(variable = "weight", selected = 1, highlight=TRUE)) 
p
```


### Assignment 1.3


```{r, warning=FALSE, echo=FALSE}


nodes1<-nodes
net <- graph_from_data_frame(d=links, vertices=nodes, directed=F)
ceb <- cluster_edge_betweenness(net) 
nodes1$group=ceb$membership
visNetwork(nodes1,links)%>%visIgraphLayout()%>%
  visPhysics(solver="repulsion")%>% 
  visOptions(highlightNearest = list(enabled = TRUE, 
             algorithm = "hierarchical",hover = TRUE, degree = 2 ),
             nodesIdSelection = list(enabled = TRUE),
             selectedBy = list(variable = "weight", selected = 1, highlight=TRUE)) 

```


### Assignment 1.4

```{r, warning=FALSE, echo=FALSE}

netm <- get.adjacency(net, attr="weight", sparse=F)
colnames(netm) <- V(net)$media
rownames(netm) <- V(net)$media

rowdist<-dist(netm)

library(seriation)
order1<-seriate(rowdist, "HC")
ord1<-get_order(order1)

reordmatr<-netm[ord1,ord1]

library(plotly)

plot_ly(z=~reordmatr, x=~colnames(reordmatr), 
        y=~rownames(reordmatr), type="heatmap")


```



# Assignment 2
### Assignment 2.1

```{r}

library(plotly)
library(gapminder)

df <- read.csv2('Oilcoal.csv')[,c(1:5)]

fig <- df %>%
  plot_ly(
    x = ~Coal, 
    y = ~Oil, 
    size = ~Marker.size, 
    color = ~Country, 
    frame = ~Year, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )
fig <- fig %>% layout(
    xaxis = list(
      type = "log"
    )
  )

fig

```


### Assignment 2.2
```{r}


fig2 <- df%>%filter(Country %in% c("United Kingdom", "Germany"))%>%
  plot_ly(
    x = ~Coal, 
    y = ~Oil, 
    size = ~Marker.size, 
    color = ~Country, 
    frame = ~Year, 
    text = ~Country, 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )
fig2 <- fig2 %>% layout(
    xaxis = list(
      type = "log"
    )
  )

fig2
 
```


### Assignment 2.3

```{r, message=FALSE}


df1 <-df
df2 <-df

df1$Oilp <- 100 * df$Oil / (df$Oil + df$Coal)
df2$Oilp  <- 0

df3 <- rbind(df1,df2)

countries_list <- c('Brazil', "US", "Germany", "United Kingdom", "France", "India", "Japan", "China")

fig3 <- df3%>%filter(Country == countries_list[1])%>%plot_ly(
    x = ~Country, 
    y = ~Oilp, 
    name = countries_list[1],
    frame = ~Year, 
    type = 'scatter',
    mode = 'line',
    line = list( width = 20)
  )
  

for(i in c(2:8)){
  
fig3 <- fig3%>%add_trace(data = df3%>%filter(Country == countries_list[i]),
                 x = ~Country,
                 y = ~Oilp,
                 name = countries_list[i],
                 line = list(width = 20))

}

fig3
```



### Assignment 2.4

```{r , message=FALSE}


fig3%>%animation_opts(100, easing = "elastic", redraw = F)

```



```{r}

df_new <- data.frame(Year=c(1965:2009))
rownames(df_new) <- df_new$Year

for (i in countries_list) {
  df_new[i] <-df%>%filter(Country==i)%>%select(Coal)
}
df_new <- df_new[, -1]

```


### Assignment 2.5

```{r , message=FALSE}

library(tourr)
library(plotly)


mat <- rescale(df_new)

set.seed(12345)
tour <- new_tour(mat, grand_tour(), NULL)
#tour<- new_tour(mat, guided_tour(cmass), NULL)

steps <- c(0, rep(1/15, 200))
Projs<-lapply(steps, function(step_size){  
  step <- tour(step_size)
  if(is.null(step)) {
    .GlobalEnv$tour<- new_tour(mat, guided_tour(cmass), NULL)
    step <- tour(step_size)
  }
  step
}
)

# projection of each observation
tour_dat <- function(i) {
  step <- Projs[[i]]
  proj <- center(mat %*% step$proj)
  data.frame(x = proj[,1], y = proj[,2], state = rownames(mat))
}

# projection of each variable's axis
proj_dat <- function(i) {
  step <- Projs[[i]]
  data.frame(
    x = step$proj[,1], y = step$proj[,2], variable = colnames(mat)
  )
}

stepz <- cumsum(steps)

# tidy version of tour data

tour_dats <- lapply(1:length(steps), tour_dat)
tour_datz <- Map(function(x, y) cbind(x, step = y), tour_dats, stepz)
tour_dat <- dplyr::bind_rows(tour_datz)

# tidy version of tour projection data
proj_dats <- lapply(1:length(steps), proj_dat)
proj_datz <- Map(function(x, y) cbind(x, step = y), proj_dats, stepz)
proj_dat <- dplyr::bind_rows(proj_datz)

ax <- list(
  title = "", showticklabels = FALSE,
  zeroline = FALSE, showgrid = FALSE,
  range = c(-1.1, 1.1)
)

# for nicely formatted slider labels
options(digits = 3)
tour_dat <- highlight_key(tour_dat, ~state, group = "A")
tour <- proj_dat %>%
  plot_ly(x = ~x, y = ~y, frame = ~step, color = I("black")) %>%
  add_segments(xend = 0, yend = 0, color = I("gray80")) %>%
  add_text(text = ~variable) %>%
  add_markers(data = tour_dat, text = ~state, ids = ~state, hoverinfo = "text") %>%
  layout(xaxis = ax, yaxis = ax)#%>%animation_opts(frame=0, transition=0, redraw = F)
tour

```

# Appendix

## Assignment 1

```

```

## Assignment 2

```


```
